### ISSUE TITLE
How display tag cloud in sidebar vector template?

### ISSUE THREAD

**Issue by poulpoulsen** [cosmocode/tagging#17]
Hello,
i try to display my tagcloud inside the template vector's sidebar.
Unfortunately i can' t see anything.
Editing tags works fine.
Displaying tags works also.
But seeing a cloud not.
If i view the page "sidebar" (on which the vector template creates the sidebar contents), i can see the cloud on the top of the page, but not inside the sidebar.
Any ideas?

Regards
Poul

**Comment by annda** [comment]
This issue references old software. If you still experience this problem, please contact the author of the Vector template.
