### ISSUE TITLE
german translation for "tag"

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [cosmocode/tagging#21]
In German the translation of "Tag" is "Schlagwort". Under programmers and software engineers the word "tag" is correctly understood, but "normal" people could perhaps misunderstand this as "day". Unfortunately there is no possibility to propose this at http://translate.dokuwiki.org/, and therefore I post it here.

Regards
Juergen

**Comment by splitbrain** [comment]
The plugin has also been added to the translation interface
