### ISSUE TITLE
Content is deleting after updating the edittable plugin

### ISSUE THREAD

**Issue by Juergen-aus-Koeln** [cosmocode/tagging#22]
After updating the edittable plugin each attempt to set a tag ends in that way, that the whole content of the page is deleted.

Regards
Juergen

**Comment by micgro42** [comment]
Hi, 

thanks for reporting this. I have a few follow-up questions: 
* What template are you using?
* Is your tagging-plugin up-to-date?
* Are you adding the new tags to a page with pre-existing tags or to a page without tags?

**Comment by Juergen-aus-Koeln** [comment]
Hi,

in my Test-Wiki I've yet switched the template to dokuwiki default. The tagging-plugin is re-installed with its current version. And I want to add a tag to a page without tags.

Best regards
Juergen

**Comment by splitbrain** [comment]
@Juergen-aus-Koeln  can you provide possible error messages from the JavaScript console please?

**Comment by Juergen-aus-Koeln** [comment]
Here are the results:

SyntaxError: invalid increment operand js.php:23:666024
ReferenceError: jQuery is not defined jquery.dataTables.min.js:160:141
ReferenceError: dTree is not defined doku.php:182:4
ReferenceError: DOKU_BASE is not defined

Regards
Juergen

**Comment by annda** [comment]
This issue references an obsolete version.
