### ISSUE TITLE
Broken in dokuwiki-2012-01-25a.tgz “Angua”

### ISSUE THREAD

**Issue by Suven** [cosmocode/tagging#3]
This plugin does not seem to work in __dokuwiki-2012-01-25a.tgz “Angua”__

What I did:
  * Took a new fresh installation of DW
  * Installed __tagging__, __ajaxloader__ and __sqlite__
  * Modified my main.php according to the installation notes

What happens:
Right after clicking the Edit-Button the site refreshes and nothing happens.
Tried it with IE 8 and a recent version of Firefox 11.

I noticed that putting an ```alert('blabla');``` right behind ```addInitEvent(function() {``` in __script.js__ did not cause any alert.

**Comment by splitbrain** [comment]
This plugin no longer uses the ajaxloader plugin. I assume this is fixed
