### ISSUE TITLE
Feature request: add tag by syntax

### ISSUE THREAD

**Issue by stefanoco** [cosmocode/tagging#30]
Would it be interesting for others the ability to add tags to a page by syntax? As an example use case:

* one page has something like `{{tagging::tag>5627fd782}}` in the sources
* anywhere else a link to that page can be created by writing `http://yourwiki/doku.php?do=tagjmp&tag=5627fd782`

When you're managing a long list of pages at the same level this can be useful.

**Comment by splitbrain** [comment]
Creating tags by syntax is kinda the opposite of what this plugin wants to achieve.
