### ISSUE TITLE
Feature request: add tags to Paragraphs

### ISSUE THREAD

**Issue by schittli** [cosmocode/tagging#31]
Good evening

I am searching for a Wiki which allows us to add one or more Tags to Paragraphs (in contrast to Pages) and I'm pretty sure there is no solution until now.

But the benefits would be great:
- Usually, one wiki page covers more than on subject - but it's hard to find the related paragraphs.
- It would be useful to collect paragraphs which are tagged by the same tag: this would be an andvanced find function or would allow to print an excerpt
- It would be useful if we could show / hide assigned Tags in a (adjustable) small Font
- While browsing for a subject, it would be useful to highlight / mark paragraphs which are tagged by specific tags
- It's possible to enhance this Paragraph-Tagging feature, e.g. if a Header is marked by Tags: all Paragraphs in this chapter are related to the same Tags. If a Tag is directly assigned to a Paragraph, then it is more important than a Tag which is added to a Header or to a Page.

Kind regards,
Thomas

**Comment by splitbrain** [comment]
Sorry. This is beyond the scope of this plugin and won't be added.
