### ISSUE TITLE
Tag search not working reliably

### ISSUE THREAD

**Issue by juliusverrel** [cosmocode/tagging#45]
Tag editing seems to work fine, but search doesn't. Some tags are found by dokuwiki search (or the search attached to each tag), and some aren't even if attached to the very same page. The behavior is consistent for each tag by itself but inconsistent across tags. It's not specific to tags with spaces or uppercase letters (which seem to be represented differently internally), it's also not the case that it breaks down at some point (if I add 7 tags, the first and last might be working, the middle ones not). 

I'm using dokuwiki with the arctic template, with {{tagging::input}} included in the sidebar. Happy to provide list of plugins. 

Many thanks for this great plugin and (hopefully) for your help!

Best, Julius

**Comment by splitbrain** [comment]
hopefully fixed now

**Comment by juliusverrel** [comment]
thanks!
