### ISSUE TITLE
per tag pages listing?

### ISSUE THREAD

**Issue by sandos187** [cosmocode/tagging#48]
Would it be possible to include a feature to list all pages given a specific tag. At the moment, the only chance to get a list of all pages tagged with a specific task is to initiate a search and get the search result.
I think it would be nice to have an aggregation feature to display all the pages like the nspages-plugin (https://www.dokuwiki.org/plugin:nspages) do. So that i get a list in alphabetical order per tag. Something like {{tagging::tag>TAGNAME}}.

Or are there other (perhaps builtin) features, that provide such nspages-style-listings for tags, which i just don't know about?

Thx in advance
Sandos

**Comment by splitbrain** [comment]
@annda can you check if #50 can be merged? I think this would be useful.

**Comment by annda** [comment]
Closing the issue after merging #50 and #59

@sandos187 Thanks for your contribution. Upstream now includes the new feature, plus a small fix in #59
