### ISSUE TITLE
Add syntax component for the tag editing form

### ISSUE THREAD

**Issue by COLABORATI** [cosmocode/tagging#8]
Hi, great tool! 
I would like to have this feature only on some pages, but not on all - can this be done and if yes, how?
Maybe it would be a better approach to add the tag input form with a syntax component on select pages?
What do you think about this?

**Comment by splitbrain** [comment]
You can surround the call by some if statement checking the current ID.

A syntax component might be useful though to add the tagging mechanism to a sidebar page.

**Comment by splitbrain** [comment]
The plugin has now a syntax component

**Comment by COLABORATI** [comment]
cool, thank you and have a nice day!
