### ISSUE TITLE
See tags for all users? -> Expanding for more generic uses.

### ISSUE THREAD

**Issue by COLABORATI** [cosmocode/tagging#9]
Maybe I am abusing your extension. I would like to offer users to make a public tag on some pages that could be seen by other users (with the same rights or higher). This should basically be a hybrid between a vote and a tag... users basically should be able to but their tag (like in graffiti) on pages where this is allowed so that others can see that this user is tagging this or that page. 

Also there should be one big page listing (table) of all pages with tags and who tagged the page. Do you think your plugin could expand into this direction or are the basic decisions made already? I did not dive into the dokuwiki code base too deep, so it would be nice if you could give me a hint if I am heading into a totally wrong direction with this extension. 

Thanks very much for your attention. 

Hey, I wrote a longer description in the dokuwiki forum:
https://forum.dokuwiki.org/post/47265

maybe from that text it is easier to understand why I see your plugin somewhere near to what I am looking for... Thanks again!

**Comment by splitbrain** [comment]
It's nothing planned for that plugin and I'm not sure it would fit it. Feel free to build your own based on it though.
